[package]
name = "hardener-plugins"
version = "0.1.0"
edition = "2024"

[dependencies]
hardener-common = { path = "../hardener-common" }
hardener-core   = { path = "../hardener-core" }
log = "0.4.28"
tempfile = { workspace = true }
tokio = { workspace = true }
tracing = "0.1.41"
anyhow = "1.0.100"
async-trait = { workspace = true }
chrono = "0.4.42"
