[package]
name = "hardener-plugins"
version.workspace = true
edition.workspace = true

[dependencies]
hardener-common = { path = "../hardener-common" }
hardener-core   = { path = "../hardener-core" }
tokio = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
