[package]
name = "hardener-state"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
# Internal dependencies
hardener-common = { workspace = true }
hardener-types = { workspace = true }

# Database
sqlx = { workspace = true }

# Async runtime
tokio = { workspace = true }

# Random
rand = "0.9.3"

# Serialisation
serde = { workspace = true }
serde_json = { workspace = true }

# Cryptography (for checkpoint signatures)
ed25519-dalek = { workspace = true }
ring = { workspace = true}

# Logging
tracing = { workspace = true }

# Error handling
nix = { workspace = true, features = ["fs"] }
chrono = { workspace = true, features = ["serde"] }
subtle = "2.6.1"
zeroize = "1.8.2"

[dev-dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
tempfile = "3.23.0"
