#!/bin/bash
set -e

case "$1" in
    configure)
        [ -d /var/lib/linux-hardener ] && chown root:root /var/lib/linux-hardener
        command -v systemctl >/dev/null && systemctl daemon-reload || true
        ;;
esac

#DEBHELPER#
