[package]
name = "hardener-types"
description = "Shared type definitions for Linux System Hardener (WASM-compatible)"
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
serde = { workspace = true }
chrono = { version = "0.4.42", features = ["serde"] }
