[package]
name = "hardener-types"
description = "Shared type definitions for Linux System Hardener (WASM-compatible)"
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
serde = { workspace = true }
chrono = { workspace = true, features = ["serde"] }

[dev-dependencies]
serde_json = { workspace = true }
