[package]
name = "hardener-core"
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
hardener-common = { workspace = true }
hardener-state = { path = "../hardener-state", optional = true }
hardener-types = { workspace = true }
hostname = { workspace = true, optional = true }
nix = { workspace = true, optional = true }
openssh = { workspace = true, optional = true }
petgraph = { workspace = true, optional = true }
serde = { workspace = true }
tracing = { workspace = true }
chrono = "0.4.42"
dirs = "6.0.0"
toml = "0.9.8"
tempfile = "3.23.0"

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[features]
default = ["system"]
system = ["hostname", "nix", "petgraph", "hardener-state", "openssh"]
