[package]
name = "hardener-core"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
hardener-common = { workspace = true }
hardener-state = { path = "../hardener-state", optional = true }
hardener-types = { workspace = true }
hostname = { workspace = true, optional = true }
nix = { workspace = true, optional = true }
openssh = { workspace = true, optional = true }
petgraph = { workspace = true, optional = true }
serde = { workspace = true }
tokio = { workspace = true, features = ["process"] }
tracing = { workspace = true }
chrono = { workspace = true }
dirs = { workspace = true }
toml = { workspace = true }
tempfile = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[features]
default = ["system"]
system = ["hostname", "nix", "petgraph", "hardener-state", "openssh"]
