#!/usr/bin/env python3
"""
Validates that `packaging/.SRCINFO` says what `packaging/PKGBUILD` declares.

`.SRCINFO` is not a document anybody edits. It is generated by
`makepkg --printsrcinfo` and it is the only file the AUR reads: the web
interface, the search index and every helper resolve a package's version,
dependencies and sources from it, never from the PKGBUILD beside it. So a
`.SRCINFO` that has fallen behind is not a cosmetic mismatch, it is the AUR
describing a package that is not the one it builds.

It had fallen behind by three releases. `pkgver` read 1.2.2 against a PKGBUILD
of 1.5.1, and the `source` line derived from it pointed at the v1.2.2 tarball.
Nothing compared them, so the drift survived every release, every validation run
and every reader, exactly like the badges did before `validate_badges.py`.

Two checks, because they fail in different ways and one of them must run
everywhere:

The first is a full regeneration, `makepkg --printsrcinfo`, compared against the
committed bytes. That is the whole truth and it catches a field this file has
never thought about. It needs `makepkg`, so it is available on an Arch host and
not on the project's Ubuntu CI.

The second parses the scalars out of the PKGBUILD directly and holds `.SRCINFO`
to them, plus asserts that no line in `.SRCINFO` carries a version string other
than `pkgver`, which is what catches the derived `source` line generically. It
needs nothing but Python, so **the check still fails on the exact drift that
happened even where `makepkg` is absent**. A validator that quietly skips itself
off-platform is a control that cannot fail, which is the failure this repository
keeps finding in its own checks.

When `makepkg` is missing that is reported as a reduced check rather than as a
pass, because a run that could not ask the question must not read like a run
that asked it and was satisfied.
"""

import re
import shutil
import subprocess
import sys
from pathlib import Path

GREEN = "\033[0;32m"
RED = "\033[0;31m"
YELLOW = "\033[1;33m"
BLUE = "\033[0;34m"
NC = "\033[0m"

PKGBUILD = Path("packaging/PKGBUILD")
SRCINFO = Path("packaging/.SRCINFO")

# The scalars .SRCINFO carries verbatim from the PKGBUILD. `pkgname` becomes
# `pkgbase` at the top of the generated file, which is why the mapping is
# written out rather than assumed.
SCALARS = {
    "pkgname": "pkgbase",
    "pkgver": "pkgver",
    "pkgrel": "pkgrel",
    "pkgdesc": "pkgdesc",
    "url": "url",
}

VERSION_PATTERN = re.compile(r"\b\d+\.\d+\.\d+\b")


def find_project_root() -> Path:
    current = Path.cwd()
    while current != current.parent:
        if (current / "Cargo.toml").exists():
            return current
        current = current.parent
    return Path.cwd()


def pkgbuild_scalars(text: str) -> dict[str, str]:
    """Reads the top-level scalar assignments, stripping one layer of quotes."""
    found = {}
    for key in SCALARS:
        match = re.search(rf'^{key}=(.*)$', text, re.M)
        if match:
            found[key] = match.group(1).strip().strip('"').strip("'")
    return found


def srcinfo_fields(text: str) -> dict[str, list[str]]:
    fields: dict[str, list[str]] = {}
    for line in text.splitlines():
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        fields.setdefault(key.strip(), []).append(value.strip())
    return fields


def check_scalars(root: Path) -> list[str]:
    pkgbuild = pkgbuild_scalars((root / PKGBUILD).read_text())
    srcinfo = srcinfo_fields((root / SRCINFO).read_text())
    problems = []

    for pkg_key, src_key in SCALARS.items():
        want = pkgbuild.get(pkg_key)
        if want is None:
            problems.append(f"{PKGBUILD} declares no {pkg_key}")
            continue
        got = srcinfo.get(src_key, [])
        if not got:
            problems.append(f"{SRCINFO} carries no {src_key}")
        elif got[0] != want:
            problems.append(
                f"{src_key} reads '{got[0]}' in {SRCINFO}, "
                f"'{want}' in {PKGBUILD}"
            )

    # The derived lines. `source` interpolates $pkgver, so a stale version
    # survives there even once the scalar is fixed by hand, and it is the line
    # the AUR fetches from.
    version = pkgbuild.get("pkgver")
    if version:
        for number, line in enumerate((root / SRCINFO).read_text().splitlines(), 1):
            for other in VERSION_PATTERN.findall(line):
                if other != version:
                    problems.append(
                        f"{SRCINFO}:{number} carries version '{other}' "
                        f"against a pkgver of '{version}': {line.strip()}"
                    )
    return problems


def check_regenerated(root: Path) -> tuple[list[str], bool]:
    """Full regeneration. Returns (problems, ran)."""
    if shutil.which("makepkg") is None:
        return [], False

    result = subprocess.run(
        ["makepkg", "--printsrcinfo"],
        cwd=root / "packaging",
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        return [f"makepkg --printsrcinfo failed: {result.stderr.strip()}"], True

    committed = (root / SRCINFO).read_text()
    if result.stdout == committed:
        return [], True

    problems = []
    want = result.stdout.splitlines()
    got = committed.splitlines()
    for number, (a, b) in enumerate(zip(got, want), 1):
        if a != b:
            problems.append(f"{SRCINFO}:{number}: committed '{a.strip()}', regenerated '{b.strip()}'")
    if len(got) != len(want):
        problems.append(
            f"{SRCINFO} has {len(got)} line(s), a regeneration produces {len(want)}"
        )
    return problems, True


def main() -> int:
    print(f"{BLUE}Validating .SRCINFO against its PKGBUILD...{NC}\n")
    root = find_project_root()

    for path in (PKGBUILD, SRCINFO):
        if not (root / path).exists():
            print(f"  {RED}x{NC} {path} does not exist")
            return 1

    problems = check_scalars(root)
    regenerated, ran = check_regenerated(root)
    problems.extend(regenerated)

    if problems:
        print(f"  {RED}.SRCINFO disagrees with {PKGBUILD}:{NC}")
        for problem in problems:
            print(f"    {RED}x{NC} {problem}")
        print(
            f"\n{RED}The AUR reads .SRCINFO and never the PKGBUILD beside it, "
            f"so this is what a user installs. Regenerate with:{NC}\n"
            f"    cd packaging && makepkg --printsrcinfo > .SRCINFO"
        )
        return 1

    print(f"  {GREEN}v{NC} Every scalar and every version string agrees with {PKGBUILD}")
    if ran:
        print(f"  {GREEN}v{NC} A regeneration reproduces the committed file byte for byte")
    else:
        print(
            f"  {YELLOW}!{NC} makepkg is not installed, so only the scalars and "
            f"version strings were compared. A field outside that set could "
            f"differ and this run would not see it."
        )

    print(f"\n{GREEN}.SRCINFO validation passed{NC}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
